### ISSUE TITLE
Project checklist

### ISSUE THREAD

**Issue by khawe** [TF-PMcardle/flight-booker#12]
See https://docs.google.com/document/d/1V79Hqmhd-ZOg4aZg5s-d8mD8JnDMKtOhzoteKZ6N__8/edit

- [x]  Rails 7 app
- [x] MySQL backend database.  
- [x] Modify the README to explain what you’re doing and link back to the project here.

**Screen 1: Search**
- [x] #13
- [x] Create an Airport model (which just needs an airport code like “SFO” or “NYC”) and use the db/seeds.rb file to create several airports.
- [x] Create a Flight model (with the departure and arrival airport ids, start datetime and flight duration).
- [x] #16
- [x] Same for Airport.first.departing_flights and Airport.first.arriving_flights, which should return a list of Flight objects.
- [x] You will search and view results in the same page. 
- [x] Set up your FlightsController and routes to make the Index page (/flights) the root route.
- [x] Create your search form on the /flights index page to submit using a GET (not POST) request back to the same URL.
- [x] Add the four dropdown menus – a list of departure airports, arrival airports, number of passengers (1-4), and a date dropdown for the flight date. The date dropdown should only include dates that have existing flights. 

**Screen 2: pick a flight**

- [x] Once search results are returned, the user just needs to choose from among the available flights.
- [x] Once the user has submitted the form, your controller should detect the additional query parameters (e.g. from /flights?departure_code=SFO&arrival_code=NYC&date=20131215&num_tickets=2) and should pull the flights which match that criteria from your database through smart querying model methods.
- [x] Send those flights back to your app/views/flights/index.html.erb view. Make it so that the view will display the results below (if present).
Don’t get rid of the search dropdowns – keep the search form active at the top so the user can try running a new search.
- [x] #18

**Screen 3: passenger information**

- [x] Once the user has submitted their chosen flight, it’s time to take their booking information. You’ll need a form to submit the Booking and also create a Passenger object for each passenger who needs a ticket. Don’t worry about creating a separate “Ticket” object, we’ll assume the airline will issue those once the booking is verified.
- [x] Create and migrate the Booking model.
- [x] Create and migrate the Passenger model (just keep the information simple – name and email only).
- [x] Set up associations between Bookings, Passengers, and Flights.
- [x] Create a BookingsController and appropriate routes.
- [x] Set up your #new action, which should have received the flight ID and passenger number parameters, and use it to help render a form for a new booking which displays the currently chosen date, airports, flight ID and a set of fields to enter personal information for each passenger. You’ll want to create a new blank Passenger object in your controller for each passenger, and then use #fields_for in the view to set up the sub-forms.
- [x] Try submitting the form and check out the parameters in your server.
You’ll need your #create action to create a new Booking (linking it to the appropriate Flight) but it will also need to accept the nested attributes for each of the Passenger objects and create a new Passenger from them. Be mindful of allowing the nested parameters as well.
- [x] Go to the Booking model and implement the #accepts_nested_attributes_for method. See the [Rails API](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html) for examples and [this SO post](http://stackoverflow.com/questions/18540679/rails-4-accepts-nested-attributes-for-and-mass-assignment) for another.
Once your form is successfully submitted, render the booking’s #show page which displays the booking information (flight and passenger information).
